export default {
    query: [
        "ian.boros",
        "martin.neupauer",
        "samuel.mercier",
        "justin.seyster",
        "misha.ivkov",
        "david.storch",
        "jacob.evans",
        "pawel.terlecki",
        "charlie.swanson",
        "george.wangensteen",
        "xinhao.zhang",
        "james.wahlin",
        "nicholas.zolnierz",
        "davis.haupt",
        "ted.tuckman",
        "bernard.gorman",
        "arun.banala",
        "anton.korshunov"
    ],
    sharding: [
        "kaloian.manassiev",
        "jason.zhang",
        "jamie.heppenstall",
        "alex.taskov",
        "blake.oler",
        "esha.maharishi",
        "jack.mulrow",
        "janna.golden",
        "matthew.saltz",
        "misha.tyulenev",
        "randolph",
        "kevin.pulo",
        "lamont.nelson",
    ],
    replication: [
        "tess.avitabile",
        "judah.schvimer",
        "jason.chan",
        "lingzhi.deng",
        "matthew.russotto",
        "pavithra.vetriselvan",
        "samy.lanka",
        "siyuan.zhou",
        "suganthi.mani",
        "vessy.ratcheva",
        "william.schultz",
        "allison.easton",
        "vishnu.kaushik",
        "medha.potluri",
    ],
    "service architecture": [
        "jason.carey",
        "ben.caimano",
        "mathias.stearn",
    ],
    "storage engines": [
        "michael.cahill",
        "alexander.gorrod",
        "vamsi.krishna",
        "donald.anderson",
        "keith.bostic",
        "luke.chen",
        "alex.cameron",
        "sasha.fedorova",
        "sue.loverso",
        "sulabh.mahajan",
        "luke.pearson",
        "haribabu.kommi",
    ],
    execution: [
        "eric.milkie",
        "geert.bosh",
        "benety.goh",
        "danel.gottlieb",
        "dianna.hohensee",
        "gregory.wlodarek",
        "louis.williams",
        "maria.vankeulen",
        "xiangyu.yao",
    ],
    security: [
        "acm",
        "spencer.jackson",
        "jonathan.reams",
        "mark.benvenuto",
        "sara.golemon",
        "shreyas.kalyan",
    ],
    "developer tools": [
        "acm",
        "adam",
        "billy.donahue",
        "gabirel.russell",
        "henrik.edin",
        "matthew.robinson",
    ],
    "triage and release": [
        "kelsey.schubert",
        "bruce.lucas",
        "danny.hatcher",
        "eric.sedor",
    ],
};

